resolvers ++= Seq(
  Resolver.typesafeRepo("releases")
)

addSbtPlugin("com.github.sbt"    % "sbt-git"             % "2.0.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.9")
addSbtPlugin("io.kamon"          % "sbt-aspectj-runner"  % "1.1.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"           % "1.5.1")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "2.0.0")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("io.gatling"        % "gatling-sbt"         % "2.2.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.10.4")
