site_name: Knora Documentation

nav:
  - Home: index.md
  - Introduction:
      - Index: 01-introduction/index.md
      - What is Knora?: 01-introduction/what-is-knora.md
      - Data Formats in Knora: 01-introduction/data-formats.md
      - Standoff/RDF Text Markup: 01-introduction/standoff-rdf.md
      - An Example Project: 01-introduction/example-project.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
    - navigation.tabs
extra_css:
  - 'assets/style/theme.css'
docs_dir: src
